package:
  name: idba
  version: "1.1.4_kwo_modified"

source:
  path: /home/kwo/wormlab_packages/idba/idba

build:
    number: 0
    string: idba

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  run:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}  

about:
  home:

